import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>the - Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>the Home</h1>
        <p>Esse fugiat velit deserunt sit velit proident nisi elit ullamco. Reprehenderit ex quis elit non deserunt magna. Incididunt duis irure officia tempor officia commodo eiusmod id do. Tempor reprehenderit ut aliquip cillum fugiat Lorem nulla velit excepteur nisi in anim dolore. Aliquip consequat labore officia reprehenderit exercitation do aliqua mollit dolor laborum. Sunt labore reprehenderit aute velit exercitation in voluptate sunt sunt excepteur exercitation. Labore dolore laborum aliqua sunt esse ea culpa velit culpa tempor.</p>
      </main>
    </div>
  )
}
